{
  "uid" : "cded42d9b3ab385b",
  "name" : "登录反向用例测试",
  "fullName" : "cases.test_login.TestLogin#test_login_failed",
  "historyId" : "daee70692129a544e4ece7a1edb1fbca",
  "time" : {
    "start" : 1615107885509,
    "stop" : 1615107887617,
    "duration" : 2108
  },
  "status" : "broken",
  "statusMessage" : "KeyError: 'error_mag'",
  "statusTrace" : "self = <cases.test_login.TestLogin object at 0x0000026E9C8ED4A8>\nhandler = (<appium.webdriver.webdriver.WebDriver (session=\"81f76f62-ef8c-4968-8399-9ed3e8a9601f\")>, <pages.page_action.PageAction object at 0x0000026E9C888F98>)\ndata = {'error_msg': '账号或密码错误', 'name': '登录-反向用例-用户名正确-密码错误', 'password': '34354658', 'username': '15191776915'}\n\n    @allure.story('钓鱼人APP自动化测试-登录模块-反向用例测试')\n    @allure.title('登录反向用例测试')\n    @pytest.mark.parametrize('data',failed_data)\n    def test_login_failed(self, handler, data):\n        logger.info('开始执行反向测试用例：{}'.format(data['name']))\n        handler[1].login(data['username'], data['password'])\n        logger.info('登录操作完成')\n>       assert handler[1].is_toast_show(data['error_mag'])\nE       KeyError: 'error_mag'\n\ncases\\test_login.py:37: KeyError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "prepare_to_login",
    "time" : {
      "start" : 1615107872396,
      "stop" : 1615107881186,
      "duration" : 8790
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "hasContent" : false,
    "stepsCount" : 0,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  }, {
    "name" : "handler",
    "time" : {
      "start" : 1615107838908,
      "stop" : 1615107872396,
      "duration" : 33488
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "hasContent" : false,
    "stepsCount" : 0,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  } ],
  "testStage" : {
    "status" : "broken",
    "statusMessage" : "KeyError: 'error_mag'",
    "statusTrace" : "self = <cases.test_login.TestLogin object at 0x0000026E9C8ED4A8>\nhandler = (<appium.webdriver.webdriver.WebDriver (session=\"81f76f62-ef8c-4968-8399-9ed3e8a9601f\")>, <pages.page_action.PageAction object at 0x0000026E9C888F98>)\ndata = {'error_msg': '账号或密码错误', 'name': '登录-反向用例-用户名正确-密码错误', 'password': '34354658', 'username': '15191776915'}\n\n    @allure.story('钓鱼人APP自动化测试-登录模块-反向用例测试')\n    @allure.title('登录反向用例测试')\n    @pytest.mark.parametrize('data',failed_data)\n    def test_login_failed(self, handler, data):\n        logger.info('开始执行反向测试用例：{}'.format(data['name']))\n        handler[1].login(data['username'], data['password'])\n        logger.info('登录操作完成')\n>       assert handler[1].is_toast_show(data['error_mag'])\nE       KeyError: 'error_mag'\n\ncases\\test_login.py:37: KeyError",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "d52036cc8f5e8ad5",
      "name" : "log",
      "source" : "d52036cc8f5e8ad5.txt",
      "type" : "text/plain",
      "size" : 3985
    } ],
    "parameters" : [ ],
    "hasContent" : true,
    "stepsCount" : 0,
    "shouldDisplayMessage" : true,
    "attachmentsCount" : 1
  },
  "afterStages" : [ {
    "name" : "handler::0",
    "time" : {
      "start" : 1615107890256,
      "stop" : 1615107896900,
      "duration" : 6644
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "hasContent" : false,
    "stepsCount" : 0,
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0
  } ],
  "labels" : [ {
    "name" : "story",
    "value" : "钓鱼人APP自动化测试-登录模块-反向用例测试"
  }, {
    "name" : "epic",
    "value" : "钓鱼人APP自动化测试"
  }, {
    "name" : "feature",
    "value" : "钓鱼人APP自动化测试-登录模块"
  }, {
    "name" : "tag",
    "value" : "@pytest.mark.usefixtures('prepare_to_login')"
  }, {
    "name" : "parentSuite",
    "value" : "cases"
  }, {
    "name" : "suite",
    "value" : "test_login"
  }, {
    "name" : "subSuite",
    "value" : "TestLogin"
  }, {
    "name" : "host",
    "value" : "LAPTOP-LSM6I36P"
  }, {
    "name" : "thread",
    "value" : "17184-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "cases.test_login"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ {
    "name" : "data",
    "value" : "{'name': '登录-反向用例-用户名正确-密码错误', 'username': '15191776915', 'password': '34354658', 'error_msg': '账号或密码错误'}"
  } ],
  "links" : [ ],
  "hidden" : true,
  "retry" : true,
  "extra" : {
    "categories" : [ ],
    "tags" : [ "@pytest.mark.usefixtures('prepare_to_login')" ]
  },
  "source" : "cded42d9b3ab385b.json",
  "parameterValues" : [ "{'name': '登录-反向用例-用户名正确-密码错误', 'username': '15191776915', 'password': '34354658', 'error_msg': '账号或密码错误'}" ]
}