{"name": "登录反向用例测试", "status": "broken", "statusDetails": {"message": "KeyError: 'error_mag'", "trace": "self = <cases.test_login.TestLogin object at 0x0000026E9C8ED3C8>\nhandler = (<appium.webdriver.webdriver.WebDriver (session=\"81f76f62-ef8c-4968-8399-9ed3e8a9601f\")>, <pages.page_action.PageAction object at 0x0000026E9C888F98>)\ndata = {'error_msg': '登录验证失败，用户不存在！', 'name': '登录-反向用例-用户名错误', 'password': '654321', 'username': '财友'}\n\n    @allure.story('钓鱼人APP自动化测试-登录模块-反向用例测试')\n    @allure.title('登录反向用例测试')\n    @pytest.mark.parametrize('data',failed_data)\n    def test_login_failed(self, handler, data):\n        logger.info('开始执行反向测试用例：{}'.format(data['name']))\n        handler[1].login(data['username'], data['password'])\n        logger.info('登录操作完成')\n>       assert handler[1].is_toast_show(data['error_mag'])\nE       KeyError: 'error_mag'\n\ncases\\test_login.py:37: KeyError"}, "attachments": [{"name": "log", "source": "3ba52ad7-2de0-4016-ab36-b1999633f2f5-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'name': '登录-反向用例-用户名错误', 'username': '财友', 'password': '654321', 'error_msg': '登录验证失败，用户不存在！'}"}], "start": 1615107883686, "stop": 1615107885427, "uuid": "20053ad5-e20d-4005-b1a8-ea653e76b433", "historyId": "28fbee3f7849e5c692210a9f12e7fe96", "testCaseId": "130e6dce60bc4ef9d882c5f0465dc1d6", "fullName": "cases.test_login.TestLogin#test_login_failed", "labels": [{"name": "story", "value": "钓鱼人APP自动化测试-登录模块-反向用例测试"}, {"name": "epic", "value": "钓鱼人APP自动化测试"}, {"name": "feature", "value": "钓鱼人APP自动化测试-登录模块"}, {"name": "tag", "value": "@pytest.mark.usefixtures('prepare_to_login')"}, {"name": "parentSuite", "value": "cases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "LAPTOP-LSM6I36P"}, {"name": "thread", "value": "17184-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "cases.test_login"}]}