{"name": "登录反向用例测试", "status": "passed", "attachments": [{"name": "log", "source": "38c906ec-02c3-4850-947b-2142cce541d0-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'name': '登录-反向用例-用户名正确-密码错误', 'username': '15191776915', 'password': '34354658', 'error_msg': '账号或密码错误'}"}], "start": 1615360839552, "stop": 1615360842357, "uuid": "9c774923-3ed7-4914-ba08-f15a48955b50", "historyId": "daee70692129a544e4ece7a1edb1fbca", "testCaseId": "130e6dce60bc4ef9d882c5f0465dc1d6", "fullName": "cases.test_login.TestLogin#test_login_failed", "labels": [{"name": "story", "value": "钓鱼人APP自动化测试-登录模块-反向用例测试"}, {"name": "feature", "value": "钓鱼人APP自动化测试-登录模块"}, {"name": "epic", "value": "钓鱼人APP自动化测试"}, {"name": "tag", "value": "@pytest.mark.usefixtures('prepare_to_login')"}, {"name": "parentSuite", "value": "cases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "LAPTOP-LSM6I36P"}, {"name": "thread", "value": "5840-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "cases.test_login"}]}